### ISSUE TITLE
CLIENT_MISSING_INTENTS error

### ISSUE THREAD

**Issue by Joseph-developer1** [AlexzanderFlores/Worn-Off-Keys-Discord-Js#27]
the bot dosent work on discord.js version 13.0.1!
it prompted an error that said:
TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
    at Client._validateOptions (C:\Users\pc\Desktop\HHF\node_modules\discord.js\src\client\Client.js:544:13)
    at new Client (C:\Users\pc\Desktop\HHF\node_modules\discord.js\src\client\Client.js:73:10)
    at Object.<anonymous> (C:\Users\pc\Desktop\HHF\index.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'CLIENT_MISSING_INTENTS'
}

**Comment by frprofessor** [comment]
got the same thing

**Comment by ghost** [comment]
Bot works only discord.js 12 version.

**Comment by Joseph-developer1** [comment]
k

**Comment by Joseph-developer1** [comment]
issue closed!
